version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: cmnisal_postgres
    environment:
      POSTGRES_USER: cmnisal
      POSTGRES_PASSWORD: cmnisal
      POSTGRES_DB: cmnisal
    ports:
      - '3009:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
